package com.shamisen.domain.entity;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.ruoyi.common.annotation.DataFill;
import lombok.Data;

/**
 *
 * @author  adonis
 */
@Data
public class BookContent implements Serializable {
    /**
     * 书籍id
     *
     */
    @TableId(type = IdType.ASSIGN_ID)
    private String bookId;

    /**
     * 书籍类别id
     *
     */
    private String typeId;

    /**
     * 书籍名称
     *
     */
    private String bookName;

    /**
     * 创建时间
     *
     */
    @TableField(fill = FieldFill.INSERT)
    @DataFill(value = "T(com.ruoyi.common.utils.DateUtils).getNowDate()",fillClass = Date.class)
    private Date createTime;

    /**
     * 更新时间
     *
     */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    @DataFill(value = "T(com.ruoyi.common.utils.DateUtils).getNowDate()",fillClass = Date.class)
    private Date updateTime;

    /**
     * 是否上架 1:代表上架 0:代表下架
     *
     */
    private Integer isUp;

    /**
     * 书籍版本
     *
     */
    private Integer version;

    /**
     * 排序字段
     *
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_content
     *
     */
    private static final long serialVersionUID = 1L;
}